#pragma once

enum BoomerangBroState {
	BOOMERANG_BRO_MOVING_LEFT, BOOMERANG_BRO_MOVING_RIGHT, BOOMERANG_BRO_POPPING_LEFT, BOOMERANG_BRO_POPPING_RIGHT, BOOMERANG_BRO_DROPPING_LEFT, BOOMERANG_BRO_DROPPING_RIGHT, BOOMERANG_BRO_BEING_DEAD
};