#pragma once

enum BossState
{
	BOSS_MOVING_LEFT, BOSS_MOVING_RIGHT, BOSS_FLYING_TOP_LEFT, BOSS_FLYING_TOP_RIGHT, BOSS_FLYING_LEFT, BOSS_FLYING_RIGHT, BOSS_DROPPING_LEFT, BOSS_DROPPING_RIGHT, BOSS_TRAMPLED, BOSS_DEAD
};