#pragma once

enum GoombaState {
	GOOMBA_STANDING, GOOMBA_MOVING_LEFT, GOOMBA_MOVING_RIGHT, GOOMBA_DROPPING_LEFT, GOOMBA_DROPPING_RIGHT, GOOMBA_POPPING_LEFT, GOOMBA_POPPING_RIGHT, GOOMBA_FLYING_LEFT, GOOMBA_FLYING_RIGHT, GOOMBA_DROPPING_LEFT_FROM_AIR, GOOMBA_DROPPING_RIGHT_FROM_AIR, TRAMPLED_GOOMBA, THROWN_LEFT_AWAY_GOOMBA, THROWN_RIGHT_AWAY_GOOMBA, DEAD_GOOMBA,
};