#pragma once

enum GoombaState {
	GOOMBA_STANDING, GOOMBA_MOVING_LEFT, GOOMBA_MOVING_RIGHT, GOOMBA_DROPPING_LEFT, GOOMBA_DROPPING_RIGHT, TRAMPLED_GOOMBA, THROWN_LEFT_AWAY_GOOMBA, THROWN_RIGHT_AWAY_GOOMBA, DEAD_GOOMBA,
};