#pragma once

enum KoopaState {
	KOOPA_STANDING, KOOPA_MOVING_LEFT, KOOPA_MOVING_RIGHT, KOOPA_SHRINKAGE, KOOPA_SHRINKAGE_MOVING_LEFT, KOOPA_SHRINKAGE_MOVING_RIGHT, KOOPA_SHRINKAGE_DROPPING_LEFT, KOOPA_SHRINKAGE_DROPPING_RIGHT, KOOPA_BEING_EARNED, KOOPA_DEAD,
};