#pragma once

enum KoopaState {
	KOOPA_STANDING, KOOPA_MOVING_LEFT, KOOPA_MOVING_RIGHT, KOOPA_DROPPING_LEFT, KOOPA_DROPPING_RIGHT, KOOPA_SHRINKAGE, KOOPA_SHRINKAGE_MOVING_LEFT, KOOPA_SHRINKAGE_MOVING_RIGHT, KOOPA_SHRINKAGE_DROPPING_LEFT, KOOPA_SHRINKAGE_DROPPING_RIGHT, KOOPA_FLYING_LEFT, KOOPA_FLYING_RIGHT, KOOPA_SHRINKAGE_SHAKING, KOOPA_THROWN_LEFT_AWAY, KOOPA_THROWN_RIGHT_AWAY, KOOPA_DEAD,
};