#pragma once

enum MarioState {
	DROPPING, JUMPING, STANDING, WALKING, DIE, DIE_JUMPING, DIE_DROPPING, SCALING_UP, SCALING_DOWN, TRANSFERING_TO_FLY, DROPPING_DOWN_PIPE, POPPING_UP_PIPE, JUMPING_UP_TO_CLOUND, DROPPING_DOWN_WIN, MOVING_RIGHT_WIN,
};

enum MarioSubState {
	NONE, PUSHING,
};