#pragma once
enum SectionFileType
{
	SECTION_NONE,
	SECTION_SETTING,
	SECTION_CAMERA,
	SECTION_MAP_INFO,
	SECTION_MAP_INDEXES,
	SECTION_MARIO_INFO,
	SECTION_MARIO_ANIMATIONS,
	SECTION_GROUNDS,
	SECTION_GIFT_BRICK_FRAMES,
	SECTION_GIFT_BRICK_ANIMATION,
	SECTION_SCORE_BOARD,
	SECTION_GRASS_ANIMATION,
	SECTION_GRASS_FRAMES,
	SECTION_WMARIO_INFO,
	SECTION_WMARIO_ANIMATION,
	SECTION_WMARIO_MOVING_MATRIX,
	SECTION_HELP_LABEL_ANIMATION,
	SECTION_HELP_LABEL_FRAME,
};